export class UseThemConfiguration{
    static PRESS_VIB=40;
    static DRAG_VIB=30;
    static IMAGE_EDIT_MID_RANGE=100;
    static IMAGE_EDIT_ZOOM_SENSITIVITY=0.05;
    static IMAGE_EDIT_ZOOM_RESPONSE_TIME=200;
    static IMAGE_EDIT_OP_DEFAULT_SIZE=800;

    static PinchZoomBlocDoubleTapTime=500;

    static IMAGE_RESIZE_SIZE_FILE_PICKER=1000;
    static IMAGE_RESIZE_QUALITY_FILE_PICKER=0.8;

    static PLAYER_INTERSECTION_RATIO_FOR_PLAY=1;
    static PLAYER_INTERSECTION_RATIO_FOR_PAUSE=1;
}